version: '3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    networks:
      mynet:
        aliases:
          - jenkins
    ports:
      - "8080:8080"


  ollama:
    image: ollamaserver
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      mynet:
        aliases:
          - ollama


networks:
  mynet:
    driver: bridge 
